infodir=usr/share/info
filelist=(libgomp.info libquadmath.info)

post_upgrade() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    [ -f $infodir/$file.gz ] || continue
    install-info $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}

pre_remove() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    [ -f $infodir/$file.gz ] || continue
    install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}
